---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplicationResource
metadata:
  name: {{ .Release.Name }}-namespace
  labels:
    app: {{ .Release.Name }}
  annotations:
    templatestacks.crossplane.io/deletion-priority: "1"
spec:
  credentialsRef:
    name: {{ .Release.Name }}-cluster
    key: kubeconfig
  template:
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: wordpress
---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplicationResource
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
  annotations:
    templatestacks.crossplane.io/deletion-priority: "1"
spec:
  credentialsRef:
    name: {{ .Release.Name }}-cluster
    key: kubeconfig
  secrets:
    - name: {{ .Release.Name }}-sql
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: {{ .Release.Name }}
      name: wordpress
      labels:
        app: wordpress
    spec:
      selector:
        matchLabels:
          app: wordpress
      template:
        metadata:
          labels:
            app: wordpress
        spec:
          containers:
            - name: wordpress
              image: {{ .Values.image | default "wordpress:4.6.1-apache" | quote }}
              env:
                - name: WORDPRESS_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      # This is the name of the secret to use to consume the secret
                      # within the managed cluster. The reason it's different from the
                      # name of the secret above is because within the managed cluster,
                      # a crossplane-managed secret is written as '{metadata.name}-{secretname}'.
                      # The metadata name is specified above for this resource, and so is
                      # the secret name.
                      name: {{ .Release.Name }}-deployment-{{ .Release.Name }}-sql
                      key: endpoint
                - name: WORDPRESS_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-deployment-{{ .Release.Name }}-sql
                      key: username
                - name: WORDPRESS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-deployment-{{ .Release.Name }}-sql
                      key: password
              ports:
                - containerPort: 80
                  name: wordpress
---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplicationResource
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
  annotations:
    templatestacks.crossplane.io/deletion-priority: "1"
spec:
  credentialsRef:
    name: {{ .Release.Name }}-cluster
    key: kubeconfig
  template:
    apiVersion: v1
    kind: Service
    metadata:
      namespace: {{ .Release.Name }}
      name: wordpress
      labels:
        app: wordpress
    spec:
      ports:
        - port: 80
      selector:
        app: wordpress
      type: LoadBalancer